### ISSUE TITLE
Exception: Could not find __NEXT_DATA__ or SIGI_STATE

### ISSUE THREAD

**Issue by xiari0703** [networkdynamics/pytok#3]
i was run video_example.py , looks like something changed with tt html ?

**Comment by bendavidsteel** [comment]
Could you share the error you're getting?

**Comment by EnzoRobaina** [comment]
> Could you share the error you're getting?

The exception is raised after iterating over a user's videos:

```python
async with PyTok() as api:
        user = api.user(username="therock")
        user_data = await user.info()
        print(user_data)

        videos = []
        async for video in user.videos():
            video_data = await video.info() # << here
            print(video_data)
```

The raised exception comes from helpers.py at line 30
```python
raise Exception("Could not find __NEXT_DATA__ or SIGI_STATE")
```

It seems like these tags are not present in the HTML, as if something has been updated.
By searching for these script ids on the DOM, they are not present

![image](https://github.com/networkdynamics/pytok/assets/9217480/00ca90a9-9cc0-47aa-bc7b-2ea1ab0029a4)

**Comment by bendavidsteel** [comment]
Okay I encountered this issue for a few user pages, but I've made a few changes to the user videos code and it seems to be working better for me. Could you try again?

**Comment by bendavidsteel** [comment]
Okay this is now also fixed for `video_example.py`!
