### ISSUE TITLE
Captcha failure

### ISSUE THREAD

**Issue by moha-ep** [networkdynamics/pytok#7]
Is the captcha solver failing?

i get the next message:
`{'code': 500, 'data': {'msg': 'VerifyErr'}, 'message': 'Unable to verify. Please try again.', 'msg_code': '500', 'msg_sub_code': 'verify_err'}`

**Comment by bendavidsteel** [comment]
I changed how we solve captcha, so this should be fixed now! Feel free to re-open if you still find problems after the last commit
